import {StyleSheet} from 'react-native';
import {Dimensions} from 'react-native';

import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';

const WIDTH = Dimensions.get('window').width;
const HEIGHT = Dimensions.get('window').height;

const categoriesStyling = StyleSheet.create({
  container: {
    backgroundColor: '#002426',
    height: Dimensions.get('screen').height,
  },
});

const changeLanguageStyling = StyleSheet.create({
  container: {flex: 1, justifyContent: 'center', backgroundColor: '#edfeff'},
  languageButtonView: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: Dimensions.get('window').height / 20,
    alignItems: 'center',
    height: Dimensions.get('window').height / 10,
    marginBottom: Dimensions.get('window').height / 15,
  },
  languageIcon: {
    borderWidth: 1,
    borderRadius: 100,
    paddingLeft: Dimensions.get('window').width / 25,
  },
  langHeadView: {
    flexDirection: 'row',
    paddingLeft: Dimensions.get('window').width / 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: Dimensions.get('window').height / 20,
  },
  langhead: {flex: 1, justifyContent: 'flex-start'},
  pickerView: {
    height: Dimensions.get('window').height / 10,
    borderWidth: 1,
    borderRadius: 50,
    borderColor: 'black',
    paddingLeft: Dimensions.get('window').width / 20,
    margin: 5,
  },
  picker: {
    height: Dimensions.get('window').height / 10,
  },
});

const changePasswordStyling = StyleSheet.create({
  scrollview: {backgroundColor: 'white'},
  mainView: {height: Dimensions.get('window').height / 10},
  sheildiconview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: Dimensions.get('window').height / 20,
    marginBottom: Dimensions.get('window').height / 15,
  },
  sheildicon: {borderWidth: 1, borderRadius: 100},
  mobileHead: {
    flexDirection: 'row',
    paddingLeft: Dimensions.get('window').width / 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: Dimensions.get('window').height / 20,
  },
  mobileText: {flex: 1, justifyContent: 'flex-start', margin: 5},
  mobileInputView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    height: Dimensions.get('window').height / 10,
    margin: 5,
  },
  oldPasswordView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    height: Dimensions.get('window').height / 10,
    elevation: 10,
    margin: 5,
  },
  errorText: {textAlign: 'justify', margin: 20, color: 'red'},
  changePasswordView: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  touchableupdate: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 90,
    width: Dimensions.get('window').width / 1.4,
    borderWidth: 1,
    marginBottom: 6,
    backgroundColor: 'black',
    marginTop: Dimensions.get('window').height / 20,
    elevation: 20,
  },
  updateText: {fontSize: responsiveFontSize(2), color: 'white'},
});

const contactUsStyling = StyleSheet.create({
  mainContainer: {
    backgroundColor: '#edfeff',
    height: Dimensions.get('screen').height,
  },
  telephoneIcon: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: -2,
  },
  telephoneIconstyle: {borderWidth: 1, borderRadius: 100},
  makecallview: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  touchableStyle: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 90,
    width: Dimensions.get('screen').width / 1.4,
    borderWidth: 1,
    marginBottom: 6,
    backgroundColor: 'black',
    marginTop: Dimensions.get('window').height / 20,
    elevation: 20,
  },
  callsupportText: {fontSize: responsiveFontSize(2), color: 'white'},
  emailView: {
    flexDirection: 'row',
    paddingLeft: Dimensions.get('window').width / 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: Dimensions.get('screen').height / 5,
  },
  emailView2: {width: Dimensions.get('window').width},
  emailText: {textAlign: 'center'},
  emailText2: {
    flex: 1,
    fontSize: responsiveFontSize(2.7),
    justifyContent: 'flex-start',
    color: 'brown',
    elevation: 10,
    zIndex: -2,
  },
});

const howitWorksStyling = StyleSheet.create({
  container: {
    backgroundColor: '#edfeff',
    height: Dimensions.get('screen').height,
  },
  scrollContainer: {backgroundColor: '#002426', padding: 20},
  text: {color: 'white'},
  gap: {height: Dimensions.get('screen').height / 6},
});

const loginStyling = StyleSheet.create({
  mainContainer: {flex: 1, justifyContent: 'center', backgroundColor: 'white'},
  loginIcon: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: Dimensions.get('window').height / 20,
    marginBottom: Dimensions.get('window').height / 15,
  },
  login: {borderWidth: 1, borderRadius: 100},
  mobileView: {
    flexDirection: 'row',
    paddingLeft: Dimensions.get('window').width / 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: Dimensions.get('window').height / 20,
  },
  mobileText: {flex: 1, justifyContent: 'flex-start', margin: 5},
  numericView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    height: Dimensions.get('window').height / 10,
    margin: 5,
  },
  numericView3: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    height: Dimensions.get('window').height / 10,
    margin: 5,
    width: Dimensions.get('window').width / 2.5,
  },
  numericView4: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    height: Dimensions.get('window').height / 10,
    margin: 5,
    width: Dimensions.get('window').width / 2.5,
  },
  numericView2: {
    flexDirection: 'row',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height / 10,
  },
  error: {textAlign: 'justify', margin: 20, color: 'red'},
  signin: {
    flexDirection: 'row',
    justifyContent: 'center',
  },

  touchLogin: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 90,
    width: Dimensions.get('window').width / 1.4,
    borderWidth: 1,
    marginBottom: 6,
    backgroundColor: 'black',
    marginTop: Dimensions.get('window').height / 20,
    elevation: 20,
  },
  touchLogin2: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 90,
    width: Dimensions.get('window').width / 1.4,
    borderWidth: 1,
    marginBottom: 6,
    backgroundColor: 'white',
    marginTop: Dimensions.get('window').height / 20,
    elevation: 20,
  },
  logintextbutton: {fontSize: responsiveFontSize(2), color: 'white'},
  logintextbutton2: {fontSize: responsiveFontSize(2), color: 'black'},
});

const mainMapScreenStyling = StyleSheet.create({
  locationIcon: {backgroundColor: '#ebebeb', marginTop: 5},
  predictions: {
    flex: 1,
    fontSize: 20,
    textAlignVertical: 'center',
    marginTop: 6,
    marginBottom: 6,
  },
  predictionFont: {fontSize: responsiveFontSize(1.8)},
  gap: {
    borderBottomColor: '#c9c9c9',
    borderBottomWidth: 1,
  },
  ActivityIndicator: {
    position: 'absolute',
    top: Dimensions.get('window').height / 2,
    left: Dimensions.get('window').width / 2.3,
  },
  saloonIcon: {
    width: 130,
    height: 130,
  },
  barsicon: {backgroundColor: 'white'},
  barsicon2: {backgroundColor: '#002a52'},
  pred: {
    position: 'absolute',
    top: Dimensions.get('screen').height / 8.4,
  },
});

const myAppointmentsStyling = StyleSheet.create({
  // ...
  appButtonContainer2: {
    elevation: 10,
    backgroundColor: 'black',
    width: Dimensions.get('window').width / 2,
    height: Dimensions.get('window').height / 12,
    borderRadius: 2,
    paddingTop: Dimensions.get('window').height / 50,
    alignContent: 'center',
  },
  salonBackHeight: {
    // height:(Dimensions.get("window").height)/6.5
    backgroundColor: '#026604',
    margin: 5,
    padding: 5,
  },
  flatListImage: {
    marginTop: 5,
    height: Dimensions.get('window').height / 3.5,
    marginHorizontal: 5,
  },
  salonInfoBack: {
    backgroundColor: '#ffe8e8',
    marginHorizontal: 5,
    marginBottom: 5,
  },
  GenderIcon: {
    justifyContent: 'center',
    backgroundColor: '#00cad1',
    borderRadius: 30,
  },
  alignRowWise: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
  },
  alignColWise: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  salonName: {
    fontSize: responsiveFontSize(3),
    fontWeight: 'normal',
    textAlign: 'center',
    color: 'black',
    fontFamily: 'verdana',
  },
  appButtonText: {
    fontSize: responsiveFontSize(2.3),
    // height:Dimensions.get('window').height/15,
    color: '#fff',
    textAlign: 'center',
    textAlignVertical: 'center',
    textTransform: 'uppercase',
  },
  salonServices: {
    paddingLeft: 5,
    color: '#0000c4',
    fontSize: responsiveFontSize(1.8),
  },
  salonServices4: {
    paddingLeft: 5,
    color: 'whitesmoke',
    fontSize: responsiveFontSize(1.8),
  },
  salonServices2: {
    paddingLeft: 5,
    color: '#002426',
    fontSize: responsiveFontSize(2.3),
  },
  salonServices3: {
    paddingLeft: 5,
    color: 'white',
    fontSize: responsiveFontSize(2.3),
  },
  salonServices4: {
    paddingLeft: 5,
    color: 'blue',
    fontSize: responsiveFontSize(2.3),
  },
  salonServices5: {
    paddingLeft: 5,
    color: 'yellow',
    fontSize: responsiveFontSize(2.3),
  },
  view: {marginBottom: Dimensions.get('window').height / 15},
  regbutton: {
    position: 'absolute',
    top: 0,
    flexDirection: 'row',
    height: Dimensions.get('window').height / 12,
    alignItems: 'center',
  },
  regbuttontouch: {
    elevation: 10,
    backgroundColor: '#545454',
    width: Dimensions.get('window').width / 2,
    height: Dimensions.get('window').height / 12,
    borderRadius: 2,
    paddingTop: Dimensions.get('window').height / 50,
    alignContent: 'center',
  },
  regbuttontouch2: {
    elevation: 10,
    backgroundColor: 'black',
    width: Dimensions.get('window').width / 2,
    height: Dimensions.get('window').height / 12,
    borderRadius: 2,
    paddingTop: Dimensions.get('window').height / 50,
    alignContent: 'center',
  },
  gap: {height: Dimensions.get('window').height / 12},
  disclaim: {
    color: 'black',
    textAlign: 'justify',
    padding: 10,
    backgroundColor: 'white',
  },
  bad: {color: 'brown'},
  mainback: {backgroundColor: '#a9ab72'},
  doneIcon: {
    justifyContent: 'center',
    backgroundColor: '#075900',
    borderRadius: 30,
  },
  doneIcon2: {
    justifyContent: 'center',
    backgroundColor: 'orchid',
    borderRadius: 30,
    padding: 25,
  },
  doneIcon3: {
    justifyContent: 'center',
    backgroundColor: 'pink',
    borderRadius: 30,
    padding: 25,
  },
  doneIcon4: {
    justifyContent: 'center',
    backgroundColor: '#03fc9d',
    borderRadius: 30,
    padding: 25,
  },
  doneIcon5: {
    justifyContent: 'center',
    backgroundColor: 'hotpink',
    borderRadius: 30,
    padding: 25,
  },
  ok: {color: 'white'},
  ok2: {color: 'black', fontSize: 16},
  crossicon: {
    justifyContent: 'center',
    backgroundColor: 'yellow',
    borderRadius: 30,
  },
  crossicon2: {
    justifyContent: 'center',
    backgroundColor: 'red',
    borderRadius: 30,
  },
  doneiconcheck: {
    justifyContent: 'center',
    backgroundColor: 'grey',
    borderRadius: 30,
  },
  saloonrtingview: {
    flexDirection: 'row',
  },
  ratingstyle: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    textAlign: 'center',
    margin: Dimensions.get('screen').height / 90,
    color: '#b8e2e6',
  },
  regView: {
    backgroundColor: '#edfeff',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    margin: Dimensions.get('window').width / 18,
    paddingBottom: Dimensions.get('window').height / 18,
    paddingTop: Dimensions.get('window').width / 7,
  },
  regtext: {
    fontSize: responsiveFontSize(2.8),
    fontWeight: 'bold',
    height: Dimensions.get('window').height / 16,
  },
  services: {
    flexDirection: 'row',
    backgroundColor: '#e0e0e0',
    width: Dimensions.get('window').width / 1.2,
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    borderTopWidth: 1,
  },
  servicestext: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    textAlign: 'auto',
    paddingLeft: 20,
    width: Dimensions.get('window').width / 2,

    paddingRight: 50,
    fontSize: responsiveFontSize(1.8),
  },
  servicestext2: {
    flexDirection: 'row',
    fontSize: responsiveFontSize(1.8),
    justifyContent: 'flex-end',
    textAlign: 'auto',
    paddingLeft: 20,
  },
  totalText: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: 'black',
    marginTop: Dimensions.get('window').height / 30,
  },
  totalText2: {
    flexDirection: 'row',
    paddingRight: 50,
    fontWeight: 'bold',
    color: 'white',
  },
  totalText3: {color: 'red', fontWeight: 'bold'},
  dirText: {color: 'darkred', margin: 5},
  confirmView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
    marginTop: 0,
  },
  confirmtouch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3b5c51',
    height: Dimensions.get('screen').height / 12,
  },
  update: {textAlign: 'center', color: 'white'},
  cancelApp: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'darkred',
    height: Dimensions.get('screen').height / 12,
  },
  cancelApptext: {textAlign: 'center', color: 'white'},
  confirmtouch2: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'green',
    height: Dimensions.get('screen').height / 12,
  },
  gap2: {
    height: Dimensions.get('window').height / 50,
    backgroundColor: 'black',
  },
  gap3: {
    height: Dimensions.get('screen').height / 2.6,
    backgroundColor: 'white',
  },
});

const notificationsStyling = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 10,
    backgroundColor: '#002426',
  },
  noHint: {textAlign: 'center', color: 'white'},
  myApps: {
    backgroundColor: '#d9fffb',
    width: Dimensions.get('window').width / 1.05,
    borderRadius: 10,
    marginBottom: 10,
  },
  gap: {flexDirection: 'row', alignContent: 'center'},
  arrange: {flexDirection: 'row', alignItems: 'center'},
  nameview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    //height:Dimensions.get('screen').height/12,
    borderWidth: 1,
    margin: Dimensions.get('screen').height / 100,
    borderRadius: 50,
  },
  text: {
    fontSize: responsiveFontSize(2.4),
    textAlign: 'center',
    margin: 5,
  },
  description: {
    flexDirection: 'row',
    paddingLeft: 5,
    color: '#002426',
    fontSize: responsiveFontSize(2.3),
    alignItems: 'flex-start',
  },
  section: {color: 'brown', fontSize: responsiveFontSize(2.4)},
  heightGap: {height: Dimensions.get('screen').height / 15},
});

const personalInfoStyling = StyleSheet.create({
  scrollview: {backgroundColor: '#edfeff'},
  userIcn: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: Dimensions.get('window').height / 20,
    alignItems: 'center',
    height: Dimensions.get('window').height / 10,
    marginBottom: Dimensions.get('window').height / 15,
  },
  userIcn2: {
    borderWidth: 1,
    borderRadius: 100,
    paddingLeft: Dimensions.get('window').width / 25,
  },
  fullnameView: {
    flexDirection: 'row',
    paddingLeft: Dimensions.get('window').width / 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: Dimensions.get('window').height / 20,
  },
  fullnametext: {flex: 1, justifyContent: 'flex-start', margin: 5},

  nameinputview: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    height: Dimensions.get('window').height / 10,
    elevation: 10,
    margin: 5,
  },
  mobilephoneview: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: Dimensions.get('window').height / 10,
    alignItems: 'center',
    height: Dimensions.get('window').height / 10,
    marginBottom: Dimensions.get('window').height / 55,
  },
  mobilephoneicn: {
    width: Dimensions.get('window').width / 5.5,
    borderWidth: 1,
    borderRadius: 100,
    paddingLeft: Dimensions.get('window').width / 17,
  },
  phoneview: {
    height: Dimensions.get('window').height / 10,
    elevation: 10,
    flexDirection: 'row',
    margin: 5,
  },
  picker: {
    height: Dimensions.get('window').height / 10,
    borderWidth: 1,
    borderRadius: 50,
    borderColor: 'black',
    paddingLeft: Dimensions.get('window').width / 20,
    margin: 5,
  },
  pickerstyle: {
    height: Dimensions.get('window').height / 10,
  },

  passview: {
    height: Dimensions.get('window').height / 10,
    elevation: 10,
    flexDirection: 'row',
    margin: 5,
  },
  errortext: {textAlign: 'justify', margin: 20, color: 'red'},
  butonview: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  touchv: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 90,
    width: Dimensions.get('window').width / 1.4,
    borderWidth: 1,
    marginBottom: 6,
    backgroundColor: 'black',

    elevation: 20,
  },
  btntext: {fontSize: responsiveFontSize(2), color: 'white'},
});

const saloonProfileStyling = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3b5c51',
  },
  backColoract: {backgroundColor: '#00ebc7'},
  disc: {fontSize: responsiveFontSize(1.7)},
  bottomBarOverall: {
    width: Dimensions.get('window').width,
    backgroundColor: '#105c43',
    flexDirection: 'row',
    alignItems: 'center',
  },
  topBarOverall: {
    width: Dimensions.get('window').width,
    backgroundColor: '#002426',
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewsTouchable: {
    width: Dimensions.get('window').width / 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewsIcon: {
    left: -12,
  },
  reviewsIconStyle: {
    backgroundColor: '#002426',
    left: 9,
  },
  galleryOverall: {
    position: 'absolute',
    right: -12,
  },
  galleryText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  galleryIcon: {
    backgroundColor: '#002426',
    color: '#002426',
  },
  alignViewRowWise: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  salonBackHeight: {
    height: Dimensions.get('window').height / 6.5,
    backgroundColor: '#d9fffb',
    marginBottom: 7,
  },
  salonInfoBack: {
    height: Dimensions.get('window').height / 3,
    backgroundColor: '#a1a1a1',
  },
  salonInfoFront: {
    height: Dimensions.get('window').height / 5.7,
    width: Dimensions.get('window').width / 1,
    backgroundColor: '#105c43',
    fontSize: responsiveFontSize(2),
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  topCard: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: 23,
    width: 90,
    borderRadius: 2,
    backgroundColor: 'red',
  },
  backColor: {backgroundColor: '#105c43'},

  alignRowWise: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
  },
  alignColWise: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  salonName: {
    fontSize: responsiveFontSize(2),
    fontWeight: 'normal',
    textAlign: 'center',
    color: '#00544b',
    fontFamily: 'verdana',
    paddingLeft: 20,
  },
  salonPrice: {
    fontSize: responsiveFontSize(2),
    padding: 5,
    fontWeight: 'normal',
    textAlign: 'justify',
    color: '#afe3e1',
    fontFamily: 'verdana',
  },
  salonPriceMin: {
    color: '#57eba9',
    fontSize: responsiveFontSize(2),
  },
  salonServices: {
    paddingLeft: 5,
    color: '#00cad1',
    fontSize: responsiveFontSize(2),
  },
  flatListImage: {
    height: Dimensions.get('window').height / 3.6,
  },
  fontView: {
    position: 'absolute',
    top: 0,
    right: -Dimensions.get('window').height / 35,
    height: 40,
    width: 70,
    borderRadius: 50,
  },
  GenderIcon: {
    justifyContent: 'center',
    backgroundColor: '#00cad1',
    borderRadius: 50,
  },
});

const settingsStyling = StyleSheet.create({
  container: {
    backgroundColor: '#002426',
    height: Dimensions.get('window').height,
  },
  margin: {marginTop: 10},
  margin2: {width: Dimensions.get('screen').width},
  settingshead: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: Dimensions.get('window').width / 20,
    backgroundColor: '#88dba2',
    elevation: 5,
    marginBottom: 5,
  },
  settingshead2: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: Dimensions.get('window').width / 20,
    backgroundColor: 'lightgreen',
    elevation: 5,
    marginBottom: 5,
  },
  caretup: {backgroundColor: '#88dba2'},
  caretup2: {backgroundColor: 'lightgreen'},
  personalinfotouch: {
    backgroundColor: '#005363',
    borderRadius: 10,
    marginHorizontal: 20,
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    elevation: 5,
    paddingLeft: Dimensions.get('window').width / 10,
    marginBottom: 5,
  },
  personalicn: {backgroundColor: '#005363'},
  security: {
    height: Dimensions.get('window').height / 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Dimensions.get('window').width / 20,
    backgroundColor: '#88dba2',
    elevation: 5,
    marginBottom: 5,
  },
  signtext: {fontSize: responsiveFontSize(2)},

  gap: {height: Dimensions.get('window').height / 5},
});

export {
  categoriesStyling,
  changeLanguageStyling,
  changePasswordStyling,
  contactUsStyling,
  howitWorksStyling,
  loginStyling,
  mainMapScreenStyling,
  myAppointmentsStyling,
  notificationsStyling,
  personalInfoStyling,
  saloonProfileStyling,
  settingsStyling,
};
